---
component: 'test'
deployment_identifier: "%{hiera('deployment_identifier')}"

work_directory: 'build'
configuration_directory: "%{hiera('work_directory')}/%{hiera('source_directory')}"

organization_id: "602e67f467852d083d43a50f"

cluster_type: "REPLICASET"

mongo_db_major_version: "4.0"

disk_size_gb: 60

number_of_shards: 1

auto_scaling:
  disk_gb:
    enabled: true
  compute:
    enabled: true
    scale_down_enabled: true

cloud_provider:
  name: "AWS"
  region_name: "EU_WEST_1"
  instance_size_name: "M10"
  disk_iops: 180
  volume_type: "STANDARD"
  backup_enabled: true
  encrypt_ebs_volume: false
  auto_scaling:
    compute:
      min_instance_size: "M10"
      max_instance_size: "M30"

database_users:
  - username: "user-1"
    password: "password-1"
    roles:
      - role_name: "readAnyDatabase"
        database_name: "admin"
        collection_name: ""
      - role_name: "readWrite"
        database_name: "specific"
        collection_name: "things"
    labels:
      important: "thing"
      something: "else"
  - username: "user-2"
    password: "password-2"
    roles:
      - role_name: "dbAdmin"
        database_name: "specific"
        collection_name: ""
    labels: {}
