---
component: 'test'
deployment_identifier: "%{hiera('seed')}"

organization_id: "602e67f467852d083d43a50f"

cloud_provider:
  name: "AWS"
  region_name: "EU_WEST_1"
  instance_size_name: "M10"
  disk_iops: 180
  volume_type: "STANDARD"
  backup_enabled: true
  auto_scaling:
    compute:
      min_instance_size: "M10"
      max_instance_size: "M30"
