---
component: 'test'
deployment_identifier: "%{hiera('deployment_identifier')}"

work_directory: 'build'
configuration_directory: "%{hiera('work_directory')}/%{hiera('source_directory')}"

organization_id: "602e67f467852d083d43a50f"

cluster_type: "REPLICASET"

provider_name: 'AWS'
provider_region_name: 'EU_WEST_1'
provider_instance_size: 'M10'

database_users:
  - username: "user-1"
    password: "password-1"
    roles:
      - role_name: "readAnyDatabase"
        database_name: "admin"
        collection_name: ""
      - role_name: "readWrite"
        database_name: "specific"
        collection_name: "things"
    labels:
      component: "%{hiera('component')}"
      deployment_identifier: "%{hiera('deployment_identifier')}"
  - username: "user-2"
    password: "password-2"
    roles:
      - role_name: "dbAdmin"
        database_name: "specific"
        collection_name: ""
    labels: {}
